import type { BuildingTypeConfig } from "../types/map";

export const CONFIG = {
  GRID_SIZE: 2000,
  ASSET_PATH: "/map-assets/",
  OPTIM_RADIUS: 600,
  BUILDING_TYPES: [
    {
      type: "Belediye Binası",
      w: 160,
      h: 120,
      db: 55,
      color: "#005ce6",
      maxCount: 1,
      minDist: 600,
      imgIcon: "government.png",
    },
    {
      type: "Hükümet Binası",
      w: 190,
      h: 160,
      db: 55,
      color: "#003380",
      maxCount: 1,
      minDist: 600,
      imgIcon: "government.png",
    },
    {
      type: "Adliye",
      w: 190,
      h: 160,
      db: 55,
      color: "#003380",
      maxCount: 1,
      minDist: 600,
      imgIcon: "government.png",
    },
    {
      type: "Üniversite Kampüsü",
      w: 384,
      h: 384,
      db: 60,
      color: "#9933ff",
      maxCount: 1,
      minDist: 700,
      imgIcon: "university.png",
    },
    {
      type: "AVM (Alışveriş Merkezi)",
      w: 320,
      h: 320,
      db: 70,
      color: "#ff3399",
      maxCount: 2,
      minDist: 500,
      imgIcon: "mall.png",
    },
    {
      type: "Devlet Hastanesi",
      w: 280,
      h: 280,
      db: 40,
      color: "#ff1a1a",
      maxCount: 2,
      minDist: 400,
      imgIcon: "hospital.png",
    },
    {
      type: "Çiftlik / Tarım Alanı",
      w: 450,
      h: 450,
      db: 35,
      color: "#99cc00",
      maxCount: 1,
      minDist: 600,
      imgIcon: "farm.png",
    },
    {
      type: "Cami",
      w: 128,
      h: 128,
      db: 50,
      color: "#00cc99",
      maxCount: 4,
      minDist: 200,
      imgIcon: "mosque.png",
    },
    {
      type: "İlkokul",
      w: 192,
      h: 128,
      db: 50,
      color: "#ff9933",
      maxCount: 3,
      minDist: 200,
      imgIcon: "ilkokul.png",
    },
    {
      type: "Lise",
      w: 256,
      h: 192,
      db: 45,
      color: "#cc6600",
      maxCount: 2,
      minDist: 250,
      imgIcon: "school.png",
    },
    {
      type: "Kütüphane",
      w: 128,
      h: 100,
      db: 35,
      color: "#3399ff",
      maxCount: 4,
      minDist: 200,
      imgIcon: "library.png",
    },
    {
      type: "Öğrenci Yurdu",
      w: 128,
      h: 192,
      db: 45,
      color: "#66ccff",
      maxCount: 4,
      minDist: 150,
      imgIcon: "dorm.png",
    },
    {
      type: "Yaşlı Bakımevi",
      w: 160,
      h: 160,
      db: 40,
      color: "#ff6666",
      maxCount: 5,
      minDist: 250,
      imgIcon: "elderly.png",
    },
    {
      type: "Fabrika / Sanayi",
      w: 384,
      h: 384,
      db: 85,
      color: "#5900b3",
      maxCount: 4,
      minDist: 400,
      imgIcon: "factory.png",
    },
    {
      type: "Rezidans (Gökdelen)",
      w: 96,
      h: 96,
      db: 50,
      color: "#00e6e6",
      maxCount: 25,
      minDist: 80,
      imgIcon: "residence.png",
    },
    {
      type: "Otopark",
      w: 96,
      h: 96,
      db: 70,
      color: "#737373",
      maxCount: 8,
      minDist: 80,
      imgIcon: "parking.png",
    },
    {
      type: "Ofis Binası",
      w: 100,
      h: 84,
      db: 55,
      color: "#ffcc00",
      maxCount: 35,
      minDist: 60,
      imgIcon: "office.png",
    },
    {
      type: "Apartman (Konut)",
      w: 48,
      h: 48,
      db: 50,
      color: "#8cd98c",
      maxCount: Infinity,
      minDist: 0,
      prob: 0.4,
      imgIcon: "apartment.png",
    },
    {
      type: "Müstakil Ev",
      w: 64,
      h: 64,
      db: 45,
      color: "#b3ffcc",
      maxCount: Infinity,
      minDist: 0,
      prob: 0.3,
      imgIcon: "house.png",
    },
    {
      type: "Çeşitli Mağazalar",
      w: 64,
      h: 64,
      db: 65,
      color: "#ffff66",
      maxCount: Infinity,
      minDist: 0,
      prob: 0.15,
      imgIcon: "store.png",
    },
    {
      type: "Kafe / Restoran",
      w: 48,
      h: 48,
      db: 60,
      color: "#ff99cc",
      maxCount: Infinity,
      minDist: 0,
      prob: 0.15,
      imgIcon: "cafe.png",
    },
  ] satisfies BuildingTypeConfig[],
} as const;